### NumPy Basics:
vectors, matrices, tensors, math operations, linear algebra module

In [2]:
import numpy as np
import cupy as cp

In [1]:
my_array = np.arange(1_000_000)
my_list = list(range(1_000_000))
array_gpu = cp.arange(1_000_000)

In [3]:
%timeit my_array2 = my_array * 2
%timeit my_list2 = [x * 2 for x in my_list]
%timeit array_gpu2 = array_gpu * 2

741 µs ± 8.09 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
50.6 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
31.7 µs ± 339 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Creating vectors: 1D

In [4]:
data = np.array([1.5, -0.1, 3])
print(data)
print(data.shape)

[ 1.5 -0.1  3. ]
(3,)


In [5]:
data2 = np.array([[1.5, -0.1, 3],
                  [0, -3, 6.5]])
print(data2)
print(data2.shape) # 2 rows, 3 columns.
print(data2.dtype)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
(2, 3)
float64


In [6]:
print(data2.astype("int"))

[[ 1  0  3]
 [ 0 -3  6]]


In [9]:
data3 = np.array([[[1.5, -0.1, 3],
                  [0, -3, 6.5]]])
print(data3)
print(data3.shape) # 1 block, 2 rows, 3 columns.
print(data3.ndim)

[[[ 1.5 -0.1  3. ]
  [ 0.  -3.   6.5]]]
(1, 2, 3)
3


In [10]:
data4 = np.array([
    [[1.5, -0.1, 3],
     [0, -3, 6.5]],

    [[2.1, 0.5, -1],
     [4.2, 3.3, 0]]
])
print(data4)
print(data4.shape) # 2 blocks, 2 rows, 3 columns.
print(data4.ndim)


[[[ 1.5 -0.1  3. ]
  [ 0.  -3.   6.5]]

 [[ 2.1  0.5 -1. ]
  [ 4.2  3.3  0. ]]]
(2, 2, 3)
3


Math operations

In [11]:
print("Vector")
print(data)
print(f"{data * 10}\n")

print("3D tensor:")
print(data4)
print(data4 * 10)

Vector
[ 1.5 -0.1  3. ]
[15. -1. 30.]

3D tensor:
[[[ 1.5 -0.1  3. ]
  [ 0.  -3.   6.5]]

 [[ 2.1  0.5 -1. ]
  [ 4.2  3.3  0. ]]]
[[[ 15.  -1.  30.]
  [  0. -30.  65.]]

 [[ 21.   5. -10.]
  [ 42.  33.   0.]]]


In [12]:
print(data3)
data3 + data3

[[[ 1.5 -0.1  3. ]
  [ 0.  -3.   6.5]]]


array([[[ 3. , -0.2,  6. ],
        [ 0. , -6. , 13. ]]])

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr # boolean ndarray

array([[False,  True, False],
       [ True, False,  True]])

Converting a regular array into a ndarray and explicitly stating the type:

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1.dtype)
print(type(arr1))

float64
<class 'numpy.ndarray'>


In [15]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
arr2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [17]:
print(arr2)
print(arr2.shape[1]) # reaching the column count

print(data4.shape)
print(data.shape[-1])

[[1 2 3 4]
 [5 6 7 8]]
4
(2, 2, 3)
3


Initializing ndarrays with predetermined numbers:

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((2, 3, 6))


array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [3]:
np.ones(18)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [20]:
np.empty((2,3,2)) # non-zero garbage values

array([[[ 15.,  -1.],
        [ 30.,   0.],
        [-30.,  65.]],

       [[ 21.,   5.],
        [-10.,  42.],
        [ 33.,   0.]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(5,20,3) # start, stop, step

array([ 5,  8, 11, 14, 17])

In [23]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
print(numeric_strings)
numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

Transposing, reshaping arrays and swap axes

In [25]:
myarray = np.arange(10)
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
myarray.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

One of the passed shape dimensions can be –1, in which case the value used for that dimension will be inferred from the data:



In [27]:
y = np.random.randn(4,)
print(y)
print(len(y.shape))
y = y.reshape(-1, 1) # keep rows the same add 1 column
print(y)
y.shape

[ 0.17045224  0.47965087 -0.31010619 -0.81974298]
1
[[ 0.17045224]
 [ 0.47965087]
 [-0.31010619]
 [-0.81974298]]


(4, 1)

convert a multi-dimensional array into a 1D array — but they differ in whether they create a copy or a view of the data.

In [28]:
arr = np.arange(15).reshape((5, 3))
print(arr)
raveled = arr.ravel()
raveled

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
raveled[5] = 6565
arr

array([[   0,    1,    2],
       [   3,    4, 6565],
       [   6,    7,    8],
       [   9,   10,   11],
       [  12,   13,   14]])

In [30]:
flattened = arr.flatten()
print(flattened)
flattened[5] = 7777
print(arr)

[   0    1    2    3    4 6565    6    7    8    9   10   11   12   13
   14]
[[   0    1    2]
 [   3    4 6565]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]


In [31]:
arr_transposed = arr.T
arr_transposed

array([[   0,    3,    6,    9,   12],
       [   1,    4,    7,   10,   13],
       [   2, 6565,    8,   11,   14]])

In [32]:
arr = np.array([[0, 1, 0],
                [1, 2, -2],
                [6, 3, 2],
                [-1, 0, -1],
                [1, 0, 1]])
print(arr.T)
print(arr)
# inner matrix product
np.dot(arr, arr.T)

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

The random module in numpy helps create arrays with random values and determine seeds.

In [33]:
np.random.seed(42)
x = np.random.rand(10, 1) * 10  # 100 samples, 1 feature
y = 3 + 2 * x + np.random.randn(10, 1) * 2
print(x)

[[3.74540119]
 [9.50714306]
 [7.31993942]
 [5.98658484]
 [1.5601864 ]
 [1.5599452 ]
 [0.58083612]
 [8.66176146]
 [6.01115012]
 [7.08072578]]


Generates random numbers drawn from the standard normal distribution (also called the standard Gaussian).

Mean (μ) = 0

Standard deviation (σ) = 1

Values are centered around 0 (most between -3 and +3)

In [34]:
samples = np.random.standard_normal(size=(4, 4))
samples


array([[-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ],
       [ 0.0675282 , -1.42474819, -0.54438272,  0.11092259],
       [-1.15099358,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722, -1.05771093]])

Concatenating, stacking and splitting

In [35]:
print(x.shape)
intercept_value = np.ones((x.shape[0], 1))
print(intercept_value)
print(intercept_value.shape)

(10, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(10, 1)


In [36]:
x_with_intercept = np.concatenate((intercept_value, x), axis=1)
x_with_intercept

array([[1.        , 3.74540119],
       [1.        , 9.50714306],
       [1.        , 7.31993942],
       [1.        , 5.98658484],
       [1.        , 1.5601864 ],
       [1.        , 1.5599452 ],
       [1.        , 0.58083612],
       [1.        , 8.66176146],
       [1.        , 6.01115012],
       [1.        , 7.08072578]])

In [37]:
x_with_intercept2 = np.concatenate((intercept_value, x), axis=0) # add rows
x_with_intercept2

array([[1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [3.74540119],
       [9.50714306],
       [7.31993942],
       [5.98658484],
       [1.5601864 ],
       [1.5599452 ],
       [0.58083612],
       [8.66176146],
       [6.01115012],
       [7.08072578]])

The arrays must have the same shape along all other axes.

For axis=0, they must have the same number of columns.

For axis=1, they must have the same number of rows.

In [38]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [39]:
# Stack arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [40]:
# Stack arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


### **Linear Algebra**

"*" = element-wise product

dot() or @ infix operator = matrix multiplication

In [41]:
np.random.seed(42)
x = np.random.randn(2, 3) # 2x3
y = np.random.rand(2 , 3)
print(f"x = \n{x}")
print(f"y = \n{y}")

x = 
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]
y = 
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [42]:
x.dot(y.T)

array([[ 0.29842502,  0.97706306],
       [-0.25509823,  0.84650401]])

In [43]:
np.dot(x, y.T)

array([[ 0.29842502,  0.97706306],
       [-0.25509823,  0.84650401]])

In [44]:
x @ y.T

array([[ 0.29842502,  0.97706306],
       [-0.25509823,  0.84650401]])

In [45]:
vector1 = np.random.rand(4,)
vector2 = np.random.rand(4,)
print(vector1.shape)

(4,)


In [46]:
np.dot(vector1, vector2)

np.float64(0.49664165675070815)

In [47]:
vector1 @ vector2

np.float64(0.49664165675070815)

In [48]:
C = np.random.rand(2, 3, 4)
D = np.random.rand(2, 4, 5)
print("\nTensor product shape:", np.matmul(C, D).shape)
# (2, 3, 5) -> Batch matrix multiplication


Tensor product shape: (2, 3, 5)


In [49]:
square_matrix = np.random.randn(4,4)
print(square_matrix)
inverse = np.linalg.inv(square_matrix)
inverse

[[-1.10633497 -1.19620662  0.81252582  1.35624003]
 [-0.07201012  1.0035329   0.36163603 -0.64511975]
 [ 0.36139561  1.53803657 -0.03582604  1.56464366]
 [-2.6197451   0.8219025   0.08704707 -0.29900735]]


array([[-0.0411569 ,  0.18416128,  0.04212436, -0.36358675],
       [-0.14340153,  0.32801179,  0.27668822,  0.08971249],
       [ 0.68619034,  1.29341842, -0.12702328, -0.34285826],
       [ 0.1661811 , -0.33535504,  0.35450187, -0.0120575 ]])

In [50]:
np.linalg.eig(inverse)

EigResult(eigenvalues=array([-0.58281354+0.j        , -0.00747416+0.48651964j,
       -0.00747416-0.48651964j,  0.74553596+0.j        ]), eigenvectors=array([[-0.3249641 +0.j        ,  0.06024692-0.48600946j,
         0.06024692+0.48600946j, -0.09583857+0.j        ],
       [-0.23142677+0.j        , -0.02098029+0.18864463j,
        -0.02098029-0.18864463j, -0.54389125+0.j        ],
       [ 0.75984051+0.j        , -0.05679208-0.51751189j,
        -0.05679208+0.51751189j, -0.81760497+0.j        ],
       [-0.51330535+0.j        , -0.67312276+0.j        ,
        -0.67312276-0.j        , -0.16284773+0.j        ]]))