In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# I. QUESTION (4 POINTS / 2 LINES)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Write Python code to:

• Reshape it into a 3x3 matrix.

• Extract the middle row.

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr = arr.reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
middle_row = arr[1]

In [5]:
middle_row

array([4, 5, 6])

 II. QUESTION (6 POINTS / 3 LINES)

In [6]:
df = pd.DataFrame({

"Name": ["Alice", "Bob", "Charlie"],

"Score": [85, 92, 88],

"Passed": [True, True, False]

})

In [7]:
df.head()

,Name,Score,Passed
0,Alice,85,True
1,Bob,92,True
2,Charlie,88,False


In [ ]:
df