In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [4]:
my_list=[1,2,3,4]
print(my_list)

[1, 2, 3, 4]


In [5]:
my_list = my_list*2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


if we multiply a list with 2 in py, it will just paste the list again

In [6]:
array = np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
array = array*2
array

array([2, 4, 6, 8])

but in a numpy array you can multiply each element directly

In [8]:
array = np.array('A')
print(array.ndim)

0


In [9]:
array = np.array(['A','B','C'])
print(array.ndim)

1


In [10]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'A'], ['F', 'G', 'A']],
                  [['1','3','4'],['7','8','9'],['10','4','3']],
                  [['A','MONEY','D'],['D','$','A'],['F','2','A']]])
print(array.ndim)
print(array.shape)

3
(3, 3, 3)


In [11]:
print(array[0][1][1]) # chain indexing


E


In [12]:
print(array[2,1,1]) # multidimensional indexing, it's faster than chain indexing


$


In [13]:
word = array[2,0,1]
print(word)

MONEY


In [14]:
word =  array[2,1,1] + array[2,0,1] + array[2,1,1]
print(word)

$MONEY$


In [15]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
# array[start:end:step]
print(array[0])
print(array[1])

[1 2 3 4]
[5 6 7 8]


In [16]:
print(array[-2]) # negative indexing also works

[ 9 10 11 12]


In [17]:
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [19]:
print(array[:,1]) # column slicing

[ 2  6 10 14]


In [20]:
array[:,2]

array([ 3,  7, 11, 15])

In [21]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [22]:
array = np.array([1,2,3]) # scalar arithmetic
array+1

array([2, 3, 4])

In [24]:
array = array*2
array

array([2, 4, 6])

In [25]:
array/2

array([1., 2., 3.])

In [26]:
array**5 # power

array([  32, 1024, 7776])

Vectorized math funcs

In [30]:
array =np.sqrt(array)
array

array([1.18920712, 1.41421356, 1.56508458])

In [33]:
np.round(array)

array([1., 1., 2.])

In [34]:
# to round down
np.floor(array)

array([1., 1., 1.])

In [35]:
# to round up
np.ceil(array)

array([2., 2., 2.])

In [36]:
np.pi

3.141592653589793

given each radius, we will compute area of circle

In [37]:
radii =np.array([1,2,3])
print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388]


element wise arithmetic

In [38]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1+array2)

[5 7 9]


In [39]:
array1-array2

array([-3, -3, -3])

In [40]:
array1*array2

array([4.75682846, 7.07106781, 9.39050748])

In [41]:
array1/array2

array([0.25, 0.4 , 0.5 ])

In [42]:
array1**array2

array([  1,  32, 729])

comparison operators

In [43]:
scores = np.array([91,55,100,73,82,64])
print(scores == 100)

[False False  True False False False]


In [45]:
scores>=60

array([ True, False,  True,  True,  True,  True])

In [46]:
scores<60

array([False,  True, False, False, False, False])

In [47]:
scores[scores<60] =0
scores

array([ 91,   0, 100,  73,  82,  64])

broadcasting is performing operations on array with different shapes
rules:
dimensions need to be the same size or
one of the dimensions need to be 1

In [50]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)


(1, 4)
(4, 1)


In [51]:
array1*array2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [53]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8]])
print(array1.shape)
print(array2.shape)
print(array1*array2)


(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [55]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])
print(array1.shape)
print(array2.shape)
array1*array2

(4, 4)
(4, 1)


array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])